# Generated by Django 4.2.30 on 2026-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_relational_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopday',
            name='topics',
            field=models.TextField(blank=True, default='', help_text='Enter one topic per line, e.g.:\nPython Crash Course for ML\nNumPy & Pandas Deep Dive'),
        ),
    ]
