# Generated by Django 4.2.11 on 2026-08-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_workshopday_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL for the post, e.g. building-your-first-llm-app', max_length=220, unique=True)),
                ('category', models.CharField(choices=[('ai-tutorials', 'AI Tutorials'), ('career', 'Career Advice'), ('case-study', 'Case Study'), ('engineering', 'Engineering'), ('news', 'News')], default='ai-tutorials', max_length=30)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog card')),
                ('lead', models.TextField(blank=True, help_text='Opening paragraph on the post page (shown larger). Falls back to the excerpt if left blank.')),
                ('emoji', models.CharField(blank=True, default='📝', help_text='Emoji shown on the card and hero when there is no image', max_length=8)),
                ('gradient_from', models.CharField(default='#2563eb', help_text='Hero gradient start colour, e.g. #2563eb', max_length=7)),
                ('gradient_to', models.CharField(default='#3b82f6', help_text='Hero gradient end colour, e.g. #3b82f6', max_length=7)),
                ('accent', models.CharField(default='#3b82f6', help_text='Category badge colour, e.g. #3b82f6', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used if no uploaded image). An image replaces the gradient + emoji hero.')),
                ('read_time', models.CharField(blank=True, default='5 min read', help_text='e.g. 5 min read', max_length=30)),
                ('published_at', models.DateField(help_text='Date shown on the post')),
                ('author_name', models.CharField(default='Raj Makhijani', max_length=100)),
                ('author_role', models.CharField(blank=True, default='Founder, ProjectsHub', max_length=150)),
                ('author_initials', models.CharField(blank=True, default='RM', help_text='Shown in the author avatar circle', max_length=4)),
                ('is_active', models.BooleanField(default=True, help_text='Show on the blog page')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this post')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, help_text='Section heading, e.g. 1. Setting up the Environment', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Section text. One paragraph per line.')),
                ('code', models.TextField(blank=True, help_text='Optional code block shown after the text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.blogpost')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
    ]
