# Generated by Django 4.2.30 on 2026-09-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('client', models.CharField(help_text='e.g. LexAI — Startup, ShopSmart — D2C Brand', max_length=150)),
                ('industry', models.CharField(help_text='e.g. LegalTech, E-Commerce, EdTech, Healthcare', max_length=100)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('summary', models.TextField(help_text='Overview card summary')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('icon_emoji', models.CharField(default='📊', max_length=10)),
                ('band_gradient', models.CharField(default='linear-gradient(135deg, #1e3a5f, #3b82f6)', max_length=100)),
                ('timeline', models.CharField(blank=True, default='4-6 Weeks', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(default='Project Inquiry', max_length=300)),
                ('message', models.TextField()),
                ('source_page', models.CharField(default='/#contact', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon code', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='e.g. /old-project/ or /portfolio/', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='e.g. /projects/ or /projects/my-slug/', max_length=255)),
                ('status_code', models.PositiveIntegerField(choices=[(301, '301 Permanent Redirect'), (302, '302 Temporary Redirect')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'URL Redirect',
                'verbose_name_plural': 'URL Redirects',
            },
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='e.g. / or /projects/ or /tools/', max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('robots', models.CharField(default='index, follow', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('target_audience', models.CharField(choices=[('student', 'Students & Beginners'), ('business', 'Startups & Businesses'), ('both', 'Both Students & Businesses')], default='both', max_length=20)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon', models.CharField(blank=True, default='bolt', max_length=50)),
                ('cta_label', models.CharField(default='Explore Services', max_length=80)),
                ('cta_url', models.CharField(default='/#contact', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ProjectsHub', max_length=100)),
                ('tagline', models.CharField(default='From Ideas to AI-Powered Products', max_length=255)),
                ('primary_email', models.EmailField(default='support@projectshub.co.in', max_length=254)),
                ('phone', models.CharField(default='+91 9213472954', max_length=50)),
                ('whatsapp_number', models.CharField(default='919213472954', max_length=50)),
                ('location', models.CharField(default='Gujarat, India (Remote-Friendly)', max_length=200)),
                ('response_time', models.CharField(default='Within 24 hours', max_length=100)),
                ('hero_headline_prefix', models.CharField(default='Real-World AI Projects &', max_length=200)),
                ('hero_headline_highlight', models.CharField(default='Free Tools', max_length=100)),
                ('hero_subtitle', models.TextField(default='Real-world AI and machine learning projects with source code and mentorship for students, plus custom AI development and automation for businesses.')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'X / Twitter'), ('email', 'Email')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('url', models.URLField()),
                ('icon_svg', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero Trust Bar'), ('numbers', 'ProjectsHub in Numbers'), ('about', 'About / Trust Section')], default='numbers', max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='e.g. 50+, 10+, < 24h, 500+', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, default='star', help_text='Icon identifier e.g. blue, purple, green, orange', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat Item',
                'verbose_name_plural': 'Stat Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='SimpleIcon slug or SVG symbol e.g. python, fastapi, pytorch', max_length=150)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. CS Student, Data Scientist, Startup Founder', max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_color', models.CharField(default='purple', help_text='purple, blue, green, cyan, orange', max_length=30)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order'], 'verbose_name': 'Blog Section', 'verbose_name_plural': 'Blog Sections'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy Contact Message', 'verbose_name_plural': 'Legacy Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='projectdiagram',
            options={'ordering': ['order'], 'verbose_name': 'Project Diagram', 'verbose_name_plural': 'Project Diagrams'},
        ),
        migrations.AlterModelOptions(
            name='projectfeature',
            options={'ordering': ['order'], 'verbose_name': 'Project Feature', 'verbose_name_plural': 'Project Features'},
        ),
        migrations.AlterModelOptions(
            name='projecthighlight',
            options={'ordering': ['order'], 'verbose_name': 'Project Highlight', 'verbose_name_plural': 'Project Highlights'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='projecttimelinephase',
            options={'ordering': ['order'], 'verbose_name': 'Project Timeline Phase', 'verbose_name_plural': 'Project Timeline Phases'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='Full markdown / HTML content if single-body'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Interactive live demo link'),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(blank=True, default='Intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text='External portfolio or documentation link'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Highlight as top featured project'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Publish status'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='project',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug e.g. ai-sentiment-analyser', max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='accent',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_initials',
            field=models.CharField(blank=True, default='RM', max_length=4),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='emoji',
            field=models.CharField(blank=True, default='📝', max_length=8),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='gradient_from',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='gradient_to',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lead',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, default='5 min read', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='case_study_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, help_text='Downloadable source code or documentation ZIP', null=True, upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, default='2-4 Weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active / Visible across site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order (lower = first)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_label',
            field=models.CharField(blank=True, default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='AI/ML Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='show_on_index',
            field=models.BooleanField(default=False, help_text='Display in featured section on homepage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Tagline on detail page', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_size',
            field=models.CharField(blank=True, default='Solo Project', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, default='2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectdiagram',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectdiagram',
            name='label',
            field=models.CharField(blank=True, default='Architecture', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdiagram',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projecthighlight',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecthighlight',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttimelinephase',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttimelinephase',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttimelinephase',
            name='phase',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttimelinephase',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='enroll_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='price_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopday',
            name='date_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopday',
            name='outcome',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='workshopday',
            name='topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workshopenrollment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshopenrollment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(help_text='Relative (e.g. /projects/) or absolute URL', max_length=255)),
                ('group', models.CharField(choices=[('main', 'Primary Top Navigation'), ('our_work', 'Mega Menu — Our Work'), ('who_we_help', 'Section Link — Who We Help'), ('how_we_help_students', 'Mega Menu — How We Help (Students)'), ('how_we_help_business', 'Mega Menu — How We Help (Businesses)'), ('footer_work', 'Footer — Our Work'), ('footer_students', 'Footer — Students'), ('footer_business', 'Footer — Businesses'), ('footer_legal', 'Footer — Legal')], default='main', max_length=40)),
                ('icon_svg', models.TextField(blank=True, help_text='Optional inline SVG or icon class')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.navigationitem')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='core.casestudy')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
            options={
                'verbose_name': 'Case Study Technology',
                'verbose_name_plural': 'Case Study Technologies',
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Revenue, MVP Delivery, Drop-off', max_length=100)),
                ('value', models.CharField(help_text='e.g. +38%, 3 Weeks, -45%', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Metric',
                'verbose_name_plural': 'Case Study Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('category_slug', models.CharField(default='all', help_text='e.g. text, dev, chat, career, seo', max_length=50)),
                ('icon', models.CharField(default='🤖', help_text='Emoji or icon code', max_length=50)),
                ('icon_bg_gradient', models.CharField(default='linear-gradient(135deg, #1e40af, #3b82f6)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/')),
                ('external_url', models.URLField(default='https://tools.projectshub.co.in/')),
                ('is_free', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='core.toolcategory')),
            ],
            options={
                'verbose_name': 'Free AI Tool',
                'verbose_name_plural': 'Free AI Tools',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.technology'),
        ),
    ]
