# Generated by Django 4.2.30 on 2026-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogcategory_casestudy_contactinquiry_faqcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='badge_color',
            field=models.CharField(blank=True, choices=[('cyan', 'Cyan / Sky Blue'), ('emerald', 'Emerald / Green'), ('purple', 'Purple / Indigo'), ('amber', 'Amber / Yellow'), ('rose', 'Rose / Red'), ('blue', 'Classic Blue')], default='cyan', help_text='Badge color styling', max_length=30),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Optional badge e.g. '50+ Projects', 'HOT', 'NEW'", max_length=40),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='description',
            field=models.CharField(blank=True, help_text='Short subtitle or card description', max_length=255),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Card banner or thumbnail image', null=True, upload_to='navigation/'),
        ),
        migrations.AddField(
            model_name='seodata',
            name='custom_json_ld',
            field=models.TextField(blank=True, help_text='Optional custom Schema.org JSON-LD override'),
        ),
        migrations.AddField(
            model_name='seodata',
            name='is_indexable',
            field=models.BooleanField(default=True, help_text='Search engine index status toggle'),
        ),
        migrations.AddField(
            model_name='seodata',
            name='schema_type',
            field=models.CharField(blank=True, default='Auto', help_text='Schema.org type: WebSite, Product, Article, Course, FAQPage, Organization', max_length=60),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='group',
            field=models.CharField(choices=[('main', 'Primary Top Navigation'), ('our_work', 'Mega Menu — Our Work (Cards)'), ('popular_tags', 'Mega Menu — Popular Tags (Bottom Pills)'), ('who_we_help', 'Section Link — Who We Help'), ('how_we_help_students', 'Mega Menu — How We Help (Students)'), ('how_we_help_business', 'Mega Menu — How We Help (Businesses)'), ('footer_work', 'Footer — Our Work'), ('footer_students', 'Footer — Students'), ('footer_business', 'Footer — Businesses'), ('footer_legal', 'Footer — Legal')], default='main', max_length=40),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Emoji or inline SVG icon'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='robots',
            field=models.CharField(default='index, follow', help_text='e.g. index, follow or noindex, nofollow', max_length=100),
        ),
    ]
