# Generated by Django 4.2.30 on 2026-09-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_navigationitem_badge_color_navigationitem_badge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique browser session token', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_phone', models.CharField(blank=True, default='', max_length=50)),
                ('service_interest', models.CharField(blank=True, default='', help_text='Detected interest (e.g. AI Projects, Mentorship)', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('page_url', models.CharField(blank=True, default='/', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active Chatting'), ('lead', 'Lead Captured 🎯'), ('resolved', 'Resolved / Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal staff notes for follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Conversation',
                'verbose_name_plural': 'Chatbot Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Visitor / User'), ('bot', 'AI Chatbot Assistant'), ('agent', 'Staff Agent')], default='user', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatbotconversation')),
            ],
            options={
                'verbose_name': 'Chatbot Message',
                'verbose_name_plural': 'Chatbot Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
