# Generated by Django 4.2.30 on 2026-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chatbotconversation_chatbotmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGuideNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this guide note or task', max_length=200)),
                ('category', models.CharField(choices=[('general', '🌟 General / Platform Overview'), ('branding', '⚙️ Branding & Site Settings'), ('navigation', '🎨 Navigation & Mega Menu'), ('projects', '🚀 Projects & Showcase'), ('tools', '🛠️ AI Tools Directory'), ('services', '💼 Services & Case Studies'), ('workshops', '🎓 3-Day Bootcamps'), ('blog', '📝 Blog & Content'), ('crm', '📬 CRM, Leads & Chatbot'), ('seo', '🔍 SEO & Redirects'), ('checklist', '📋 Operational Checklist')], default='general', max_length=30)),
                ('content', models.TextField(help_text='Detailed instructions, operational steps, or reference notes')),
                ('action_url', models.CharField(blank=True, default='', help_text='Optional admin or site URL to take action directly', max_length=300)),
                ('action_label', models.CharField(blank=True, default='', help_text="Button text (e.g. 'Edit Site Settings', 'Add Project')", max_length=100)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to the top of the guide')),
                ('is_completed', models.BooleanField(default=False, help_text='Mark checklist item as completed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Guide Note',
                'verbose_name_plural': 'Admin Guide Notes',
                'ordering': ['-is_pinned', 'order', '-created_at'],
            },
        ),
    ]
