# Generated by Django 4.2.30 on 2026-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminguidenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuTag',
            fields=[
            ],
            options={
                'verbose_name': 'Popular Tag (Mega Menu)',
                'verbose_name_plural': 'Popular Tags (Mega Menu)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.navigationitem',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_browse_all_text',
            field=models.CharField(blank=True, default='Browse All Projects →', help_text="CTA text in 'Our Work' mega menu footer", max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_browse_all_url',
            field=models.CharField(blank=True, default='/projects/', help_text="CTA link destination in 'Our Work' mega menu footer", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_popular_label',
            field=models.CharField(blank=True, default='Popular:', help_text="Label preceding bottom tags in 'Our Work' mega menu (e.g. 'Popular:' or 'Trending:')", max_length=60),
        ),
    ]
