# Generated by Django 4.2.30 on 2026-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_megamenutag_sitesettings_mega_browse_all_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ml', 'Machine Learning'), ('backend', 'Backend'), ('data', 'Data'), ('cloud', 'Cloud')], db_index=True, default='ml', max_length=50),
        ),
    ]
