# Generated by Django 4.2.30 on 2026-09-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aitool_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingfeature',
            options={'ordering': ['order'], 'verbose_name': 'Pricing Feature', 'verbose_name_plural': 'Pricing Features'},
        ),
        migrations.AddField(
            model_name='projectdiagram',
            name='image_url',
            field=models.URLField(blank=True, help_text='External diagram URL if not uploading file'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External screenshot URL if not uploading file'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('ml', 'Machine Learning'), ('backend', 'Backend'), ('data', 'Data'), ('cloud', 'Cloud')], db_index=True, default='ml', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Select or create categories managed under Projects > Categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='projectdiagram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/diagrams/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/detail/'),
        ),
    ]
