# Generated by Django 4.2.30 on 2026-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_google_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('default', 'ProjectsHub Cyber Pro (Dark Edition)'), ('edulight', 'EduModern (Soft Violet Light Edition)')], default='default', help_text='Active frontend theme. Can be managed in Appearance > Themes.', max_length=30),
        ),
    ]
