# Generated by Django 4.2.30 on 2026-09-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_sitesettings_active_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title displayed in WordPress admin and browser tab', max_length=255)),
                ('slug', models.SlugField(help_text="URL slug (e.g. 'about', 'contact', or 'home')", max_length=255, unique=True)),
                ('content', models.TextField(blank=True, default='', help_text='Classic content or fallback HTML body')),
                ('template', models.CharField(choices=[('default', 'Default Template'), ('front_page', 'Front Page / Modular Landing'), ('full_width', 'Full Width (No Sidebar)'), ('landing', 'Landing Page (Clean Canvas)'), ('canvas', 'Blank Canvas / ACF Builder')], default='default', max_length=50)),
                ('acf_blocks', models.JSONField(blank=True, default=list, help_text='ACF Blocks / Flexible Content payload stored as JSON array')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('trash', 'Trash')], default='published', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Page hierarchy order in menus')),
                ('is_front_page', models.BooleanField(default=False, help_text="Check to set this page as the main homepage ('/')")),
                ('featured_image', models.ImageField(blank=True, help_text='Featured header or social share banner', null=True, upload_to='pages/')),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO Meta Title (defaults to title)', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='SEO Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='User author who published the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
