# Generated by Django 4.2.30 on 2026-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL slug (e.g. 'about', 'contact', or 'home')", max_length=255, unique=True),
        ),
    ]
