# Generated by Django 4.2.30 on 2026-09-18 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminguidenote',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Detailed instructions, operational steps, or reference notes'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client',
            field=models.CharField(blank=True, default='', help_text='e.g. LexAI — Startup, ShopSmart — D2C Brand', max_length=150),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='industry',
            field=models.CharField(blank=True, default='', help_text='e.g. LegalTech, E-Commerce, EdTech, Healthcare', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Overview card summary'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags e.g. PyTorch, FastAPI, AWS', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, default='Client', help_text='e.g. CS Student, Data Scientist, Startup Founder', max_length=150),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='date',
            field=models.CharField(blank=True, default='Upcoming Weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workshopcard',
            name='time',
            field=models.CharField(blank=True, default='10:00 AM - 1:00 PM IST', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopday',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='workshopday',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
